//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SendService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SendService.SendSoap")]
    public interface SendSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSimpleSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string[]> SendSimpleSMSAsync(string username, string password, string[] to, string from, string text, bool isflash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSimpleSMS2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> SendSimpleSMS2Async(string username, string password, string to, string from, string text, bool isflash);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSms", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SendService.SendSmsResponse> SendSmsAsync(SendService.SendSmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendWithDomain", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> SendWithDomainAsync(string username, string password, string to, string from, string text, bool isflash, string domainName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSmsPrice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<double> GetSmsPriceAsync(string username, string password, int irancellCount, int mtnCount, string from, string text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCredit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<double> GetCreditAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDelivery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> GetDeliveryAsync(long recId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDelivery2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> GetDelivery2Async(string recId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMultiDelivery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SendService.GetMultiDeliveryResponse> GetMultiDeliveryAsync(SendService.GetMultiDeliveryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMultiDelivery2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string[]> GetMultiDelivery2Async(string recId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDeliveries", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int[]> GetDeliveriesAsync(long[] recIds, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDeliveries2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> GetDeliveries2Async(string recId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDeliveries3", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int[]> GetDeliveries3Async(string[] recId, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInboxCount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> GetInboxCountAsync(string username, string password, bool isRead);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getMessages", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        System.Threading.Tasks.Task<SendService.MessagesBL[]> getMessagesAsync(string username, string password, int location, string from, int index, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendByBaseNumber", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        System.Threading.Tasks.Task<string> SendByBaseNumberAsync(string username, string password, string[] text, string to, int bodyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendByBaseNumber2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        System.Threading.Tasks.Task<string> SendByBaseNumber2Async(string username, string password, string text, string to, int bodyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendByBaseNumber3", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        System.Threading.Tasks.Task<string> SendByBaseNumber3Async(string username, string password, string text, string to);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendSms", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendSmsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string[] to;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string from;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string text;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public bool isflash;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string udh;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public long[] recId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] status;
        
        public SendSmsRequest()
        {
        }
        
        public SendSmsRequest(string username, string password, string[] to, string from, string text, bool isflash, string udh, long[] recId, byte[] status)
        {
            this.username = username;
            this.password = password;
            this.to = to;
            this.from = from;
            this.text = text;
            this.isflash = isflash;
            this.udh = udh;
            this.recId = recId;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendSmsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendSmsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int SendSmsResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public long[] recId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] status;
        
        public SendSmsResponse()
        {
        }
        
        public SendSmsResponse(int SendSmsResult, long[] recId, byte[] status)
        {
            this.SendSmsResult = SendSmsResult;
            this.recId = recId;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMultiDelivery", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetMultiDeliveryRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string recId;
        
        public GetMultiDeliveryRequest()
        {
        }
        
        public GetMultiDeliveryRequest(string recId)
        {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMultiDeliveryResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetMultiDeliveryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetMultiDeliveryResult;
        
        public GetMultiDeliveryResponse()
        {
        }
        
        public GetMultiDeliveryResponse(byte[] GetMultiDeliveryResult)
        {
            this.GetMultiDeliveryResult = GetMultiDeliveryResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MessagesBL : BaseBL
    {
        
        private long msgIDField;
        
        private int userIDField;
        
        private int linkIDField;
        
        private int numberIDField;
        
        private double tariffField;
        
        private byte msgTypeField;
        
        private string bodyField;
        
        private string udhField;
        
        private System.DateTime sendDateField;
        
        private string senderField;
        
        private string receiverField;
        
        private int firstLocationField;
        
        private int currentLocationField;
        
        private int partsField;
        
        private bool isFlashField;
        
        private bool isReadField;
        
        private bool isUnicodeField;
        
        private double creditField;
        
        private int moduleField;
        
        private int recCountField;
        
        private int recFailedField;
        
        private int recSuccessField;
        
        private bool isMoneyBackField;
        
        private int userStepedMasterField;
        
        private int userMasterField;
        
        private int moneyBackCountField;
        
        private int moneyBackLevelField;
        
        private System.Nullable<bool> autoSpeechTextField;
        
        private System.Nullable<int> shareServiceBodyIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long MsgID
        {
            get
            {
                return this.msgIDField;
            }
            set
            {
                this.msgIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int UserID
        {
            get
            {
                return this.userIDField;
            }
            set
            {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int LinkID
        {
            get
            {
                return this.linkIDField;
            }
            set
            {
                this.linkIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int NumberID
        {
            get
            {
                return this.numberIDField;
            }
            set
            {
                this.numberIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public double Tariff
        {
            get
            {
                return this.tariffField;
            }
            set
            {
                this.tariffField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public byte MsgType
        {
            get
            {
                return this.msgTypeField;
            }
            set
            {
                this.msgTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Body
        {
            get
            {
                return this.bodyField;
            }
            set
            {
                this.bodyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Udh
        {
            get
            {
                return this.udhField;
            }
            set
            {
                this.udhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public System.DateTime SendDate
        {
            get
            {
                return this.sendDateField;
            }
            set
            {
                this.sendDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Sender
        {
            get
            {
                return this.senderField;
            }
            set
            {
                this.senderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Receiver
        {
            get
            {
                return this.receiverField;
            }
            set
            {
                this.receiverField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int FirstLocation
        {
            get
            {
                return this.firstLocationField;
            }
            set
            {
                this.firstLocationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int CurrentLocation
        {
            get
            {
                return this.currentLocationField;
            }
            set
            {
                this.currentLocationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int Parts
        {
            get
            {
                return this.partsField;
            }
            set
            {
                this.partsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public bool IsFlash
        {
            get
            {
                return this.isFlashField;
            }
            set
            {
                this.isFlashField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public bool IsRead
        {
            get
            {
                return this.isReadField;
            }
            set
            {
                this.isReadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public bool IsUnicode
        {
            get
            {
                return this.isUnicodeField;
            }
            set
            {
                this.isUnicodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public double Credit
        {
            get
            {
                return this.creditField;
            }
            set
            {
                this.creditField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public int Module
        {
            get
            {
                return this.moduleField;
            }
            set
            {
                this.moduleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public int RecCount
        {
            get
            {
                return this.recCountField;
            }
            set
            {
                this.recCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public int RecFailed
        {
            get
            {
                return this.recFailedField;
            }
            set
            {
                this.recFailedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public int RecSuccess
        {
            get
            {
                return this.recSuccessField;
            }
            set
            {
                this.recSuccessField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public bool IsMoneyBack
        {
            get
            {
                return this.isMoneyBackField;
            }
            set
            {
                this.isMoneyBackField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public int UserStepedMaster
        {
            get
            {
                return this.userStepedMasterField;
            }
            set
            {
                this.userStepedMasterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public int UserMaster
        {
            get
            {
                return this.userMasterField;
            }
            set
            {
                this.userMasterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public int MoneyBackCount
        {
            get
            {
                return this.moneyBackCountField;
            }
            set
            {
                this.moneyBackCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public int MoneyBackLevel
        {
            get
            {
                return this.moneyBackLevelField;
            }
            set
            {
                this.moneyBackLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=27)]
        public System.Nullable<bool> AutoSpeechText
        {
            get
            {
                return this.autoSpeechTextField;
            }
            set
            {
                this.autoSpeechTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=28)]
        public System.Nullable<int> ShareServiceBodyID
        {
            get
            {
                return this.shareServiceBodyIDField;
            }
            set
            {
                this.shareServiceBodyIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MessagesBL))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BaseBL
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public interface SendSoapChannel : SendService.SendSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public partial class SendSoapClient : System.ServiceModel.ClientBase<SendService.SendSoap>, SendService.SendSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SendSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(SendSoapClient.GetBindingForEndpoint(endpointConfiguration), SendSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SendSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SendSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SendSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SendSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SendSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string[]> SendSimpleSMSAsync(string username, string password, string[] to, string from, string text, bool isflash)
        {
            return base.Channel.SendSimpleSMSAsync(username, password, to, from, text, isflash);
        }
        
        public System.Threading.Tasks.Task<string> SendSimpleSMS2Async(string username, string password, string to, string from, string text, bool isflash)
        {
            return base.Channel.SendSimpleSMS2Async(username, password, to, from, text, isflash);
        }
        
        public System.Threading.Tasks.Task<SendService.SendSmsResponse> SendSmsAsync(SendService.SendSmsRequest request)
        {
            return base.Channel.SendSmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<string> SendWithDomainAsync(string username, string password, string to, string from, string text, bool isflash, string domainName)
        {
            return base.Channel.SendWithDomainAsync(username, password, to, from, text, isflash, domainName);
        }
        
        public System.Threading.Tasks.Task<double> GetSmsPriceAsync(string username, string password, int irancellCount, int mtnCount, string from, string text)
        {
            return base.Channel.GetSmsPriceAsync(username, password, irancellCount, mtnCount, from, text);
        }
        
        public System.Threading.Tasks.Task<double> GetCreditAsync(string username, string password)
        {
            return base.Channel.GetCreditAsync(username, password);
        }
        
        public System.Threading.Tasks.Task<int> GetDeliveryAsync(long recId)
        {
            return base.Channel.GetDeliveryAsync(recId);
        }
        
        public System.Threading.Tasks.Task<int> GetDelivery2Async(string recId)
        {
            return base.Channel.GetDelivery2Async(recId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SendService.GetMultiDeliveryResponse> SendService.SendSoap.GetMultiDeliveryAsync(SendService.GetMultiDeliveryRequest request)
        {
            return base.Channel.GetMultiDeliveryAsync(request);
        }
        
        public System.Threading.Tasks.Task<SendService.GetMultiDeliveryResponse> GetMultiDeliveryAsync(string recId)
        {
            SendService.GetMultiDeliveryRequest inValue = new SendService.GetMultiDeliveryRequest();
            inValue.recId = recId;
            return ((SendService.SendSoap)(this)).GetMultiDeliveryAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<string[]> GetMultiDelivery2Async(string recId)
        {
            return base.Channel.GetMultiDelivery2Async(recId);
        }
        
        public System.Threading.Tasks.Task<int[]> GetDeliveriesAsync(long[] recIds, string username, string password)
        {
            return base.Channel.GetDeliveriesAsync(recIds, username, password);
        }
        
        public System.Threading.Tasks.Task<int> GetDeliveries2Async(string recId)
        {
            return base.Channel.GetDeliveries2Async(recId);
        }
        
        public System.Threading.Tasks.Task<int[]> GetDeliveries3Async(string[] recId, string username, string password)
        {
            return base.Channel.GetDeliveries3Async(recId, username, password);
        }
        
        public System.Threading.Tasks.Task<int> GetInboxCountAsync(string username, string password, bool isRead)
        {
            return base.Channel.GetInboxCountAsync(username, password, isRead);
        }
        
        public System.Threading.Tasks.Task<SendService.MessagesBL[]> getMessagesAsync(string username, string password, int location, string from, int index, int count)
        {
            return base.Channel.getMessagesAsync(username, password, location, from, index, count);
        }
        
        public System.Threading.Tasks.Task<string> SendByBaseNumberAsync(string username, string password, string[] text, string to, int bodyId)
        {
            return base.Channel.SendByBaseNumberAsync(username, password, text, to, bodyId);
        }
        
        public System.Threading.Tasks.Task<string> SendByBaseNumber2Async(string username, string password, string text, string to, int bodyId)
        {
            return base.Channel.SendByBaseNumber2Async(username, password, text, to, bodyId);
        }
        
        public System.Threading.Tasks.Task<string> SendByBaseNumber3Async(string username, string password, string text, string to)
        {
            return base.Channel.SendByBaseNumber3Async(username, password, text, to);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SendSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.SendSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SendSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://api.payamak-panel.com/post/Send.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.SendSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://api.payamak-panel.com/post/Send.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            SendSoap,
            
            SendSoap12,
        }
    }
}
